#!/bin/bash
set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/.common.sh"

export GOEXPERIMENT=jsonv2

go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
go install github.com/kyoh86/richgo@latest
go install github.com/mfridman/tparse@latest
go install github.com/vladopajic/go-test-coverage/v2@latest
go install github.com/jstemmer/go-junit-report/v2@latest
go install golang.org/x/tools/cmd/goimports@latest
go install golang.org/x/tools/cmd/benchcmp@latest
go install golang.org/x/tools/cmd/godoc@latest
go install golang.org/x/vuln/cmd/govulncheck@latest
go install github.com/oligot/go-mod-upgrade@latest
go install github.com/Zxilly/go-size-analyzer/cmd/gsa@latest
# Packages required to generate grpc/protobuf/docs
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
go install github.com/mwitkow/go-proto-validators/protoc-gen-govalidators@latest
go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest

echo -e "${BLUE}❯ ${CYAN}Installing task ...${RESET}"
cd /usr
curl -sL 'https://taskfile.dev/install.sh' | sh

rm -rf "$(go env GOPATH)/.cache/go-build"
echo -e "${BLUE}❯ ${GREEN}Tools install completed${RESET}"
